### ISSUE TITLE
Launch Place Picker Take a Time 

### ISSUE THREAD

**Issue by sohijain** [androidmads/PlacePickerSample#1]
Hi,

I am using place picker API i didn't understand why it takes a time when it will be launch first time??
after one time launch when we again open second time it is proper.

**Comment by androidmads** [comment]
Hi Sohijain, 
I thought, already you got the solution here.

[https://stackoverflow.com/questions/46599081/first-time-launch-google-place-picker-take-a-time](https://stackoverflow.com/questions/46599081/first-time-launch-google-place-picker-take-a-time)
